library(curatedMetagenomicData)
curatedMetagenomicData("YachidaS_2019.relative_abundance",dryrun=F)
curatedMetagenomicData("ZellerG_2014.relative_abundance",dryrun=F)
curatedMetagenomicData("RaymondF_2016.pathway_abundance",dryrun=F)
curatedMetagenomicData("RaymondF_2016.gene_families",dryrun=F)
